  GNU nano 6.2                              docker-compose.yml                                        version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=  # Set a root password for MySQL
      - MYSQL_DATABASE=timesheet_db  # Name of the database to be created
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    volumes:
      - db:/var/lib/mysql  # Persist MySQL data

  tp-foyer:
    depends_on:
      - mysqldb  # Ensure MySQL starts before your application
    image: akremcherif/tp-foyer:1.0  # Use your Docker image
    restart: on-failure
    ports:
      - "8082:8082"  # Map port 8082 for your Spring Boot app
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/timesheet_db?createDatabaseIfNotExist=tr>        "spring.datasource.username"  : "root",
        "spring.datasource.password"  : null,  # Use the same password as above
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:  # Define a volume for MySQL data persistence
